---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-app
rules:
- apiGroups: ["cert-manager.io"]
  resources: ["certificaterequests"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-app
subjects:
- kind: ServiceAccount
  name: example-app