---
helmDefaults:
  wait: true
  timeout: 300
---

releases:
- name: web-app
  version: "v0.1.0"
  chart: ./web-app
  namespace: default
  values:
  - spiffeTrustDomain: {{ requiredEnv "SPIFFE_TRUST_DOMAIN" }}
  - validSA:
    - "frontend"
 #   - "frontend-2"    