{{- define "sds.name" -}}
{{- printf "spiffe://%s/ns/%s/sa/%s" .std .ns .sdsSA }}
{{- end -}}
node:
  id: {{ .id | quote }}
  cluster: "demo-cluster-spire"
static_resources:
  listeners:
  - name: local_service
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 9001
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            idle_timeout: 1s
          forward_client_cert_details: sanitize_set
          set_current_client_cert_details:
              uri: true
          codec_type: auto
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: "/tmp/inbound-proxy.log"
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: local_service
          http_filters:
          - name: envoy.filters.http.router
            typed_config: 
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: {{ include "sds.name" . | quote }}
              sds_config:
                resource_api_version: V3
                path_config_source:
                  path: /run/envoy/sds.yaml
                  watched_directory:
                    path: /run/envoy
            combined_validation_context:
              # validate the SPIFFE ID of incoming clients
              default_validation_context:
                match_typed_subject_alt_names:
                {{- range .validSA }}
                - san_type: URI
                  matcher:
                    exact: {{ printf "spiffe://%s/ns/%s/sa/%s" $.std $.ns . | quote }}
                {{- end }}
              # obtain the trust bundle from SDS
              validation_context_sds_secret_config:
                name: {{ printf "spiffe://%s" .std | quote }}
                sds_config:
                  resource_api_version: V3
                  path_config_source:
                    path: /run/envoy/sds-validation.yaml
            tls_params:
              ecdh_curves:
                - X25519:P-256:P-521:P-384
  clusters:
  - name: local_service
    connect_timeout: 1s
    type: strict_dns
    load_assignment:	
      cluster_name: local_service
      endpoints:	
      - lb_endpoints:	
        - endpoint:	
            address:	
              socket_address:	
                address: 127.0.0.1
                port_value: 8080
