apiVersion: v1
kind: Service
metadata:
  name: redis-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-app.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
   - port: 6000
     protocol: TCP
     targetPort: 6000
     name: envoy
  {{- if .Values.perfTesting.enable }}
   - port: 6379
     protocol: TCP
     targetPort: 6379
     name: redis
  {{- end }}
  selector:
      app: redis-server
