---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-app.labels" . | nindent 4 }}
    app: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      serviceAccountName: redis-server
      containers:
      - name: envoy
        image: {{ .Values.envoy.image }}
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml"]
        ports:
        - containerPort: 6000
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true
        - name: spiffe
          mountPath: /run/spiffe
          readOnly: true
        - name: spiffe-ca
          mountPath: /run/spiffe-ca
          readOnly: true
      - name: redis-server
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - "/redis-master/redis.conf"
        volumeMounts:
        - name: redis-data
          mountPath: "/redis-master-data"
        - name: redis-config
          mountPath: "/redis-master"
        - name: redis-dump
          mountPath: "/data"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: envoy-config
        configMap:
          name: redis-envoy
      - name: spiffe
        csi:
          driver: spiffe.csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            spiffe.csi.cert-manager.io/fs-group: "1000"
      - name: spiffe-ca
        configMap:
          name: csi-driver-spiffe-bundle
      - name: redis-data
        emptyDir: {}
      - name: redis-dump
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
