---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - name: envoy
        image: {{ .Values.envoy.image }}
        imagePullPolicy: Always
        args: ["-l", "debug", "--local-address-ip-version", "v4", "-c", "/run/envoy/envoy.yaml"]
        ports:
        - containerPort: 9001
        volumeMounts:
        - name: envoy-config
          mountPath: "/run/envoy"
          readOnly: true
        - name: spiffe
          mountPath: /run/spiffe
          readOnly: true
        - name: spiffe-ca
          mountPath: /run/spiffe-ca
          readOnly: true
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: backend-balance-json-data
          mountPath: "/usr/share/nginx/html/balances"
          readOnly: true
        - name: backend-profile-json-data
          mountPath: "/usr/share/nginx/html/profiles"
          readOnly: true
        - name: backend-transactions-json-data
          mountPath: "/usr/share/nginx/html/transactions"
          readOnly: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: envoy-config
        configMap:
          name: backend-envoy
      - name: spiffe
        csi:
          driver: spiffe.csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            spiffe.csi.cert-manager.io/fs-group: "1000"
      - name: spiffe-ca
        configMap:
          name: csi-driver-spiffe-bundle
      - name: backend-balance-json-data
        configMap:
          name: backend-balance-json-data
      - name: backend-profile-json-data
        configMap:
          name: backend-profile-json-data          
      - name: backend-transactions-json-data
        configMap:
          name: backend-transactions-json-data
