apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-transactions-json-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  transaction_1: |-
    {
      "transactions": [
        {
          "description": "Kohls: Crhistmas decorations",
          "debit": 20
        },
        {
          "description": "Alms from the collections",
          "credit": 450
        },
        {
          "description": "Khols: Christmas cards",
          "debit": 20
        },
        {
          "description": "Cash withdrawl",
          "debit": 600
        },
        {
          "description": "Pay from employer",
          "credit": 6000
        },
        {
          "description": "Health Insurance: Tiny Tim",
          "debit": 5000
        },
        {
          "description": "Opening Balance",
          "debit": 10000
        }

      ]
    }
  transaction_2: |-
    {
      "transactions": [
        {
          "description": "Kohls: Crhistmas decorations",
          "debit": 20
        },
        {
          "description": "Alms from the collections",
          "credit": 450
        },
        {
          "description": "Khols: Christmas cards",
          "debit": 20
        },
        {
          "description": "Cash withdrawl",
          "debit": 300
        },
        {
          "description": "Pay from employer",
          "credit": 600
        },
        {
          "description": "Health Insurance: Tiny Tim",
          "debit": 500
        },
        {
          "description": "Opening Balance",
          "debit": 1000
        }

      ]
    }