apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  sds-validation.yaml: |-
    {{ tpl (.Files.Get "config/sds-validation.yaml") . }}
  sds.yaml: |-
    {{ tpl (.Files.Get "config/sds.yaml") (dict "std" .Values.spiffeTrustDomain "ns" .Release.Namespace "sa" "backend" "Template" $.Template) }}
  envoy.yaml: |-
    {{ tpl (.Files.Get "config/backend-envoy.yaml") (dict "std" .Values.spiffeTrustDomain "id" "backend" "ns" .Release.Namespace "sdsSA" "backend" "validSA" .Values.validSA "Template" $.Template) | nindent 4 }}