apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-2-envoy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  sds-validation.yaml: |-
    {{ tpl (.Files.Get "config/sds-validation.yaml") . }}
  sds.yaml: |-
    {{ tpl (.Files.Get "config/sds.yaml") (dict "std" .Values.spiffeTrustDomain "ns" .Release.Namespace "sa" "frontend-2" "Template" $.Template) }}
  envoy.yaml: |-
    {{ tpl (.Files.Get "config/frontend-envoy.yaml") (dict "std" .Values.spiffeTrustDomain "id" "frontend-2" "ns" .Release.Namespace "sdsSA" "frontend-2" "validSA" "backend" "obProxyPort" "3003" "Template" $.Template) | nindent 4 }}