apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  ports:
   - port: 80
     name: http
     protocol: TCP
     targetPort: 3000
  selector:
      app: frontend
  type: ClusterIP