apiVersion: v1
kind: Service
metadata:
  name: frontend-2
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  ports:
   - port: 80
     name: http
     protocol: TCP
     targetPort: 3002
  selector:
      app: frontend-2
  type: ClusterIP