apiVersion: v1
kind: ConfigMap
metadata:
  name: symbank-webapp-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
data:
  symbank-webapp.conf: |-
    {{- tpl (.Files.Get "config/symbank-webapp.conf") . | nindent 4 }}